version: 0.1.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: >-
    dotnet restore

    choco install opencover.portable

    choco install codecov
build:
  verbosity: minimal
test_script:
- ps: >-
    dotnet test .\BitcoinShow.Test\

    OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\BitcoinShow.Test\bin\Release\netcoreapp2.0\BitcoinShow.Test.dll -noshadow" -filter:"+[BitcoinShow.Web*]* -[BitcoinShow.Test*]*" -output:".\BitcoinShow_coverage.xml"

    ls

    codecov -f "BitcoinShow_coverage.xml"
