version: 0.1.{build}
branches:
  only:
  - develop
  - master
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: >-
    dotnet restore
    
    choco install xunit
    
    choco install opencover.portable
    
    choco install codecov
build:
  project: BitcoinShow.MVC.sln  
  verbosity: minimal
test_script:
- ps: >-
    dotnet test .\BitcoinShow.Test\
    
    OpenCover.Console.exe -register:user -target:"dotnet test" -targetargs:".\BitcoinShow.Test\BitcoinShow.Test.csproj" -filter:"+[BitcoinShow.Web*]* -[BitcoinShow.Test*]*" -output:".\BitcoinShow_coverage.xml"
    
    codecov -f "BitcoinShow_coverage.xml"
